--- DATABASE FOR UNION BANK LOAN APPLICATION SYSTEM


--I FIRST CREATED THE DATABASE
CREATE DATABASE UNION_BANK;
USE UNION_BANK;

--I THEN CREATED THE BORRROWER AND LOAN SCHEMA
CREATE SCHEMA BORROWER;
CREATE SCHEMA LOAN;

--I NOW CREATED A BORROWER TABLE IN THE BORROWER SCHEMA TO CAPTURE BASIC INFORMATION ABOUT THE BORROWER
CREATE TABLE BORROWER.BORROWER
 (
  BorrowerID INT NOT NULL,
  BorrowerFirstName VARCHAR (255) NOT NULL,
  BorrowerMiddleInital CHAR (1) NOT NULL,
  BorrowerLastName VARCHAR (255) NOT NULL,
  DOB DATETIME NOT NULL,
  Gender CHAR (1) NULL,
  TaxPayerID_SSN VARCHAR (9) NOT NULL,
  PhoneNumber VARCHAR (10) NOT NULL,
  Email VARCHAR (255) NOT NULL,
  Citizenship VARCHAR (255) NULL,
  BeneficiaryName VARCHAR (255) NULL,
  IsUScitizen bit null,
  CreateDate datetime not null,
  AddressID int null
  );


  -- I THEN ADDED A SSN COLUMN TO THE TABLE
  ALTER TABLE BORROWER.BORROWER
  ADD SSN VARCHAR (9) NOT NULL;

  -- I MADE THE BORROWERID COLUMN OUR UNIQUE IDENTIFIER
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT PK_BORROWER_BORROWERID PRIMARY KEY (BorrowerID);

  --NUMBER OF DIGITS ENTERED IN THE PHONENUMBER COLUMN MUST BE EXACTLY 10
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT CHK_BORROWER_PHONENUMBER CHECK (LEN(PhoneNumber)=10);

--NUMBER OF DIGITS ENTERED IN THE SSN COLUMN MUST BE EXACTLY 9
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT CHK_BORROWER_SSN CHECK (LEN(SSN)=9);

  -- THE EMAIL SHOULD INCLUDE THE '@' SYMBOL
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT CHK_BORROWER_EMAIL_CONTAINS_AT CHECK (Email LIKE '%@%');
  
  --I ENSURED ALL BORROWERS MUST BE 18 YEARS OR OLDER AS OF DATE OF ENTRY
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT CHK_BORROWER_DOB18 CHECK ( DOB <= DATEADD(YEAR, -18, GETDATE()));

  --IF NO DATE IS ADDED TO THE CREATE DATE COLUMN, IT SHOULD AUTOMATICALLY USE THE CURRENT DATE AND TIME
  ALTER TABLE BORROWER.BORROWER
  ADD CONSTRAINT DF_BORROWER_CREATEDATE DEFAULT (GETDATE()) FOR [CreateDate];

  -- I WENT ON TO CREATE A BORROWER ADDRESS TABLE ALSO IN THE BORROWER SCHEMA
  CREATE TABLE BORROWER.BORROWERADDRESS

  ( 
   AddressID INT NOT NULL,
   BorrowerID INT NOT NULL,
   StreetAddress VARCHAR (255) NOT NULL,
   Zip VARCHAR (5) NOT NULL,
   CreateDate DATETIME NULL
   );

   -- I CHOSE ADDRESSID AND BORROWERID TO BE OUR UNIQUE IDENTIFIERS IN THIS TABLE
   ALTER TABLE BORROWER.BORROWERADDRESS
   ADD CONSTRAINT PK_BORROWERADDRESS_ADDRESSID_BORROWERID PRIMARY KEY (AddressID, BorrowerID); 
   
   --I CHOSE BORROWERID AS THE FOREIGN KEY FOR BORROWER ADDRESS TABLE AND THE BORROWER TABLE
   ALTER TABLE BORROWER.BORROWERADDRESS
   ADD CONSTRAINT FK_BORROWER_ADDRESS_BORROWERID FOREIGN KEY (BorrowerID) REFERENCES [BORROWER].[BORROWER] (BorrowerID);
   

   -- I MADE ZIP THE FOREIGN KEY FOR THE BORROWER ADDRESS TABLE AND THE US_ZIPCODES TABLE AS REQUIRED
    ALTER TABLE BORROWER.BORROWERADDRESS
	ADD CONSTRAINT FK_BORROWER_ADDRESS_ZIP FOREIGN KEY (Zip) REFERENCES [dbo].[US_ZipCodes] (Zip);

-- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
  ALTER TABLE  BORROWER.BORROWERADDRESS
  ADD CONSTRAINT DF_BORROWER_ADDRESS_CREATEDATE DEFAULT (GETDATE()) FOR [CreateDate];

  -- I CREATED A CALANDER TABLE IN THE DEFAULT SCHEMA (dbo)
   CREATE TABLE Calendar
   (
    CalendarDate DATETIME NULL
	);

	--I CREATED A STATE TABLE IN THE DEFAULT SCHEMA (dbo)
	CREATE TABLE State
	(
	 StateID CHAR (2) NOT NULL,
	 StateName VARCHAR (255) NOT NULL,
	 CreateDate DATETIME NOT NULL
	 );
	 
	 -- STATE ID AS THE UNIQUE IDENTIFIER
	 ALTER TABLE STATE
	 ADD CONSTRAINT PK_STATE PRIMARY KEY (StateID);

	 -- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
	 ALTER TABLE STATE
	 ADD CONSTRAINT DF_STATE_CREATEDATE DEFAULT (GETDATE()) FOR [CreateDate];

	 -- THE STATENAME COLUMN SHOULD ONLY TAKE UNIQUE VALUES AND NO DUPLICATE
	  ALTER TABLE STATE
	  ADD CONSTRAINT UQ_STATE_STATENAME UNIQUE(StateName);

	  -- CREATED THE US_ZIPCODES TABLE IN THE DEFAULT SCHEMA (dbo)
	 CREATE TABLE US_ZipCodes
	 (
	  IsSurrogateKey INT NOT NULL,
	  Zip VARCHAR (5) NOT NULL,
	  Latitude FLOAT NULL,
	  Longitude FLOAT NULL,
	  City VARCHAR (255) NULL,
	  StateID CHAR (2) NULL,
	  Population INT NULL,
	  Density DECIMAL NULL,
	  County_fips VARCHAR (10) NULL,
	  County_name VARCHAR (255) NULL,
	  County_name_all VARCHAR (255) NULL,
	  County_fips_all VARCHAR (50) NULL,
	  Timezone VARCHAR (255) NULL,
	  CreateDate DATETIME NOT NULL
	  );

	  --  SETTING THE NUMBER PRECISION AND SCALE REQUIRED FOR THE DENSITY COLUMN WHERE 18 IS THE NUMERIC PRECISION AND 0 THE SCALE
	  ALTER TABLE [dbo].[US_ZipCodes]
	  ALTER COLUMN Density DECIMAL(18,0);

	  -- ZIP AS THE UNIQUE IDENTIFIER
	   ALTER TABLE dbo.US_ZipCodes
	   ADD CONSTRAINT PK_US_ZIPCODES_ZIP PRIMARY KEY (Zip);

	    -- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
	   ALTER TABLE [dbo].[US_ZipCodes]
	   ADD CONSTRAINT DF_DBO_ZIPCODES_CREATEDATE DEFAULT (GETDATE()) FOR [CreateDate];

      --I CHANGED THE DATA TYPE TO INT BECAUSE IT HAD TO MATCH THE DATA TYPE OF 'UNDERWRITERID' IN THE UNDERWRITER TABLE
	    ALTER TABLE dbo.US_ZipCodes
		ALTER COLUMN StateID INT NULL;

	   -- STATEID COLUMN REFERENCING THE UNDERWRITERID COLUMN IN THE UNDERWRITER TABLE
	   ALTER TABLE dbo.US_ZipCodes
	   ADD CONSTRAINT FK_US_ZIPCODES FOREIGN KEY (StateID) REFERENCES [LOAN].[Underwriter] (UnderwriterID);

      -- CREATED THE LOAN SETUP INFORMATION TABLE IN THE LOAN SCHEMA
	  CREATE TABLE LOAN.LoanSetupInformation
	  (
	   IsSurrogateKey INT NOT NULL,
	   LoanNumber VARCHAR (10) NOT NULL,
	   PurchaseAmount NUMERIC (18,2) NOT NULL,
	   PurchaseDate DATETIME NOT NULL,
	   LoanTerm INT NOT NULL,
	   BorrowerID INT NOT NULL,
	   UnderWriterID INT NOT NULL,
	   ProductID CHAR (2) NOT NULL,
	   INTRESTRATE DECIMAL (3,2) NOT NULL,
	   PaymentFrequency INT NOT NULL,
	   AppraisalValue NUMERIC (18,2) NOT NULL,
	   CreateDate DATETIME NOT NULL,
	   LTV DECIMAL (4,2) NOT NULL,
	   FirstintrestPaymentDate DATETIME NULL,
	   MaturityDate DATETIME NOT NULL
	   );

	   --LOANNUMBER AS THE UNIQUE IDENTIFIER
	   ALTER TABLE LOAN.LoanSetupInformation
	   ADD CONSTRAINT  PK_LOANSETUPINFORMATION_LOANNUMBER PRIMARY KEY (LoanNumber);

	   
	    -- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
	   ALTER TABLE  LOAN.LoanSetupInformation
        ADD CONSTRAINT DF_LOAN_SETUPINFORMATION_CREATE_DATE DEFAULT (GETDATE()) FOR[CreateDate];

		-- USED A CHECK CONSTRAINT TO ENSURE LOANTERM COLUMN ONLY ALLOWS THESE NUMBERS
		ALTER TABLE LOAN.LoanSetupInformation
		ADD CONSTRAINT CHK_LOANSETUP_INFORMATION_LOANTERM CHECK (LoanTerm IN('35','30','15','10'));

		
		-- USED A CHECK CONSTRAINT TO ENSURE INTEREST RATE COLUMN ONLY ALLOWS NUMBERS BTW 0.01 AND 0.30
		ALTER TABLE LOAN.LoanSetupInformation
		ADD CONSTRAINT CHK_LOANSETUP_INFORMATION_INTRESTRATE CHECK (INTRESTRATE >= 0.01 AND INTRESTRATE <= 0.30);

		--BORROWER ID COLUMN IN THE LOAN SETUP INFORMATION TABLE REFERENCING BORROWERID COLUMN IN THE BORROWER TABLE
		ALTER TABLE LOAN.LoanSetupInformation
		ADD CONSTRAINT FK_LOAN_LOANSETUPINFORMATION_BORROWERID FOREIGN KEY (BorrowerID) REFERENCES [BORROWER].[BORROWER] (BorrowerID);

		--PAYMENT FREQUENCY IN THE LOAN SETUP INFORMATION TABLE REFERENCING PAYMENT FREQUENCY  IN THE LU_PAYMENT FREQUENCY TABLE
		ALTER TABLE LOAN.LoanSetupInformation
		ADD CONSTRAINT FK_LOAN_LOANSETUPINFORMATION_PAYMENTFREQUENCY FOREIGN KEY (PaymentFrequency) REFERENCES [LOAN].[LU_PaymentFrequency] (PaymentFrequency);

		--UNDERWRITERID COLUMN IN THE LOAN SETUP INFORMATION TABLE REFERENCING UNDERWRITERID COLUMN IN THE UNDERWRITER TABLE
		ALTER TABLE LOAN.LoanSetupInformation
		ADD CONSTRAINT FK_LOAN_LOANSETUPINFORMATION_UNDERWRITERID FOREIGN KEY (UnderWriterID) REFERENCES [LOAN].[Underwriter] (UnderWriterID);

		-- I CREATED LOAN PERIODIC TABLE IN THE DEFAULT SCHEMA (dbo)
	   CREATE TABLE LOAN.Loanperiodic
	   (
	    Issurrogatekey INT NOT NULL,
		LoanNumber VARCHAR (10) NOT NULL,
		Cycledate DATETIME NOT NULL,
		Extramonthlypayment NUMERIC (18,2) NOT NULL,
		Unpaidprincipalbalance NUMERIC (18,2) NOT NULL,
		Beginningschedulebalance NUMERIC (18,2) NOT NULL,
		Paidinstallment NUMERIC (18,2) NOT NULL,
		Intrestportion NUMERIC (18,2) NOT NULL,
		Principalportion NUMERIC (18,2) NOT NULL,
		Endschedulebalance NUMERIC (18,2) NOT NULL,
		Actualschedulebalance NUMERIC (18,2) NOT NULL,
		Totalintreestaccured NUMERIC (18,2) NOT NULL,
		Totalprincipalaccured NUMERIC (18,2) NOT NULL,
		DEFAULTPENALTY NUMERIC (18,2) NOT NULL,
		Delinquencycode INT NOT NULL,
		Createdate DATETIME NOT NULL
		);

		--LOANNUMBER AND CYCLE DATE COLUMN AS THE UNIQUE IDENTIFIERS IN THIS TABLE
		ALTER TABLE LOAN.Loanperiodic
		ADD CONSTRAINT PK_LOANPERIODIC_LOANNUMBER_CYCLEDATE PRIMARY KEY (LoanNumber, Cycledate);

		-- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
		ALTER TABLE  LOAN.Loanperiodic
        ADD CONSTRAINT DF_LOAN_PERIODIC_CREATE_DATE DEFAULT (GETDATE()) FOR[Createdate];

		-- IF NO VALUE IS ENTER, IT SHOULD DEFAULT TO 0
		ALTER TABLE LOAN.Loanperiodic
		ADD CONSTRAINT DF_LOAN_PERIODIC_EXTRAMONTHLYPAYMENTS DEFAULT (0) FOR [Extramonthlypayment];

		--LOANNUMBER COLUMN IN THE LOANPERIODIC TABLE IS REFERENCING LOANNUMBER COLUMN IN THE LOANSETUP INFORMATION TABLE
		ALTER TABLE LOAN.Loanperiodic
		ADD CONSTRAINT FK_LOAN_LOANPERIODIC_LOANNUMBER FOREIGN KEY (LoanNumber) REFERENCES [LOAN].[LoanSetupInformation] (LoanNumber);
	   
	   -- DELINQUENCYCODE COLUMN IN THE LOANPERIODIC TABLE REFERENCING DELINQUENCYCODE COLUMN IN THE DELINQUENCY TABLE
	    ALTER TABLE LOAN.Loanperiodic
		ADD CONSTRAINT FK_LOAN_LOANPERIODIC_DELINQUENCYCODE FOREIGN KEY (Deliquencycode) REFERENCES [LOAN].[LU_Delinquency] (Deliquencycode);

		-- PAID INSTALLMENTS = INTETREST PORTION + PRINCIPAL PORTION
		ALTER TABLE LOAN.Loanperiodic
		ADD CONSTRAINT CHK_LOAN_LOANPERIODIC CHECK ([Intrstportion]+[Principalportion]=[Paidinstallment]);

		-- CREATED LU_DELINQUENCY TABLE IN THE LOAN SCHEMA
	   CREATE TABLE LOAN.LU_Delinquency
	   (
	    Delinquencycode INT NOT NULL,
		Delinquency VARCHAR (255) NOT NULL
		);

		-- DELINQUENCYCODE COLUMN AS THE UNIQUE IDENTIFIER FOR THIS TABLE
		ALTER TABLE LOAN.LU_Delinquency
		ADD CONSTRAINT PK_LOAN_LU_DELINQUENCY_DELINQUENCY PRIMARY KEY (Deliquencycode);
		
		-- CREATED LU_PAYMENTFREQUENCY TABLE IN THE LOAN SCHEMA
		CREATE TABLE LOAN.LU_PaymentFrequency
		(
		 PaymentFrequency INT NOT NULL,
		 PaymentisMadeEvery INT NOT NULL,
		 PaymentFrequency_Description VARCHAR (255)
		 );
		 
		 -- PAYMENTFREQUENCY AS THE UNIQUE IDENTIFIER
		 ALTER TABLE LOAN.LU_PaymentFrequency
		 ADD CONSTRAINT PK_LOAN_LU_PAYMENTFREQUENCY PRIMARY KEY (Paymentfrequency);

		 --CREATED THE UNDERWRITER TABLE IN THE LOAN SCHEMA
		CREATE TABLE LOAN.Underwriter
		(
		 UnderwriterID INT NOT NULL,
		 UnderwriterFirstName VARCHAR (255) NULL,
		 UnderwriterMiddleinitial CHAR (1) Null,
		 PhoneNumber VARCHAR (14) NULL,
		 Email VARCHAR (255) NOT NULL,
		 CreateDate DATETIME NOT NULL,
		 UnderwriterLastName VARCHAR (255) NOT NULL
		 );
		
		-- UNDERWRITERID AS THE UNIQUE IDENTIFIER IN THIS TABLE
		ALTER TABLE LOAN.Underwriter
		ADD CONSTRAINT PK_LOAN_UNDERWRITER PRIMARY KEY (UnderwriterID);

   	-- IF NO DATE IS ENTERED, IT SHOULD DEFAULT TO THE CURRENT DATE/TIME
		ALTER TABLE LOAN.Underwriter
		ADD CONSTRAINT DF_LOAN_UNDERWRITER_CREATEDATE DEFAULT (GETDATE()) FOR [CreateDate];

		-- EMAIL SHOULD CONTAIN '@' SYMBOL
		  ALTER TABLE LOAN.Underwriter
          ADD CONSTRAINT CHK_UNDERWRITER_EMAIL_CONTAINS_AT CHECK (EMAIL LIKE '%@%');







