--DATABASE CREATION FOR UNION_BANK---

CREATE DATABASE UNION_BANK;

USE UNION_BANK;

--CREATION OF SCHEMA--
--This schema is created to store the table of the database


CREATE SCHEMA BORROWER;

CREATE SCHEMA LOAN;

--CREATION OF TABLE---
--This tables was created to store the information of unionbank customers for borrowers

CREATE TABLE BORROWER.BORROWERINFO
(
BORROWERID INT NOT NULL,
BORROWERFIRSTNAME VARCHAR(255) NOT NULL,
BORROWERMIDDLEINITIAL CHAR(1) NOT NULL,
BORROWERLASTNAME VARCHAR(255) NOT NULL,
DOB DATETIME NOT NULL,
GENDER CHAR(1) NULL,
TAXPAYERID_SSN VARCHAR(9) NOT NULL,
PHONENUMBER VARCHAR(10) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
CITIZENSHIP VARCHAR(225),
BENEFICIARYNAME VARCHAR(255),
ISUSCITIZEN BIT NULL,
CREATEDATE DATETIME NOT NULL
);

CREATE TABLE BORROWER.BORROWERADDRESS
(
ADDRESSID INT NOT NULL,
BORROWERID INT NOT NULL,
STREETADDRESS VARCHAR(255) NOT NULL,
ZIP VARCHAR(5) NOT NULL,
CREATEDATE DATETIME NOT NULL
); 

--This table was created for loan information

CREATE TABLE LOAN.LOAN_SETUP_INFORMATION
(
ISSURROGATEKEY INT NOT NULL,
LOANNUMBER VARCHAR(10) NOT NULL,
PURCHASEAMOUNT NUMERIC(18,2) NOT NULL,
PURCHASEDATE DATETIME NOT NULL,
LOANTERM INT NOT NULL,
BORROWERID INT NOT NULL,
UNDERWRITERID INT NOT NULL,
PRODUCTID CHAR(2) NOT NULL,
INTERESTRATE DECIMAL(3,2) NOT NULL,
PAYMENTFREQUENCY INT NOT NULL,
APPRAISALVALUE NUMERIC(18,2) NOT NULL,
CREATEDATE DATETIME NOT NULL,
LTV DECIMAL(4,2) NOT NULL,
FIRSTINTERESTPAYMENTDATE DATETIME NULL,
MATURITYDATE DATETIME NOT NULL
);

CREATE TABLE LOAN.LOAN_PERIODIC
(
ISSURROGATEKEY INT NOT NULL,
LOANNUMBER VARCHAR(10) NOT NULL,
CYCLEDATE DATETIME NOT NULL,
EXTRAMONTHPAYMENT NUMERIC(18,2) NOT NULL,
UNPAIDPRINCIPALBALANCE NUMERIC(18,2) NOT NULL,
BEGINNINGSCHEDULEBALANCE NUMERIC(18,2) NOT NULL,
PAIDINSTALLMENT NUMERIC(18,2) NOT NULL,
INTERESTPORTION NUMERIC(18,2) NOT NULL,
PRINCIPALPORTION NUMERIC(18,2) NOT NULL,
ENDSCHEDULEBALANCE NUMERIC(18,2) NOT NULL,
ACTUALENDSCHEDULEBALANCE NUMERIC(18,2) NOT NULL,
TOTALINTERESTACCURED NUMERIC(18,2) NOT NULL,
TOTALPRINCIPALACCURED NUMERIC(18,2) NOT NULL,
DEFAULTPENALTY NUMERIC(18,2) NOT NULL,
DELINQUENCYCODE NUMERIC(10,0) NOT NULL,
CREATEDATE DATETIME NOT NULL
);

---We alter the datatype of the column called delinquencycode in the loan periodic table because we had to use it as a foregin key to
--reference another of our table created---


ALTER TABLE [LOAN].[LOAN_PERIODIC]
ALTER COLUMN [DELINQUENCYCODE] INT NOT NULL;

CREATE TABLE LOAN.LU_DELINQUENCY
(
DELINQUENCYCODE INT NOT NULL,
DELINQUENCY VARCHAR(255) NOT NULL
);

CREATE TABLE LOAN.LU_PAYMENTFREQUENCY
(
PAYMENTFREQUENCY INT NOT NULL,
PAYMENTISMADEEVERY INT NOT NULL,
PAYMENTFREQUENCY_DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE LOAN.UNDERWRITER
(
UNDERWRITERID INT NOT NULL,
UNDERWRITERFIRSTNAME VARCHAR(255) NULL,
UNDERWRITERINITIAL CHAR(1) NULL,
UNDERWRITERLASTNAME VARCHAR(255) NOT NULL,
PHONENUMBER VARCHAR(14) NULL,
EMAIL VARCHAR(255) NOT NULL,
CREATEDATE DATETIME NOT NULL
);

--We also created a Default table. default table are table created without a schema 


CREATE TABLE CALENDER
(
CALENDER DATETIME NULL
);

CREATE TABLE STATE
(
STATEID CHAR(2) NOT NULL,
STATENAME VARCHAR(255) NOT NULL,
CREATEDATE DATETIME NOT NULL
);

CREATE TABLE US_ZIPCODES
(
ISSURROGATE INT NOT NULL,
ZIP VARCHAR(5) NOT NULL,
LATITUDE FLOAT NULL,
CITY VARCHAR(255) NULL,
STATE_ID CHAR(2) NULL,
POPULATION INT NULL,
DENSITY DECIMAL(18,0) NULL,
COUNTY_FIPS VARCHAR(10) NULL,
COUNTY_NAME VARCHAR(255) NULL,
COUNTY_NAME_ALL VARCHAR NULL,
COUNTY_FIPS_ALL VARCHAR(50) NULL,
TIMEZONE VARCHAR(255) NULL,
CREATEDATE DATETIME NOT NULL
);

--ALTERING TABLES--
--We altered our table to add a primary key unique identifier to our tables 

ALTER TABLE BORROWER.BORROWERINFO
ADD CONSTRAINT PK_BORROWERINFO_BORROWERID PRIMARY KEY (BORROWERID);

ALTER TABLE BORROWER.BORROWERADDRESS
ADD CONSTRAINT PK_BORROWERADDRESS_BORROWERID PRIMARY KEY (ADDRESSID,BORROWERID);

ALTER TABLE [LOAN].[LU_DELINQUENCY]
ADD CONSTRAINT PK_DELINQUENCY_CODE PRIMARY KEY ([DELINQUENCYCODE]);

ALTER TABLE [LOAN].[LU_PAYMENTFREQUENCY]
ADD CONSTRAINT PK_PAYMENT_FREQUENCY PRIMARY KEY ([PAYMENTFREQUENCY]);

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT PK_SETUP_INFORMATION PRIMARY KEY ([LOANNUMBER]);

ALTER TABLE [dbo].[STATE]
ADD CONSTRAINT PK_STATE PRIMARY KEY ([STATEID]);

ALTER TABLE [LOAN].[UNDERWRITER]
ADD CONSTRAINT PK_UNDERWRITER PRIMARY KEY ([UNDERWRITERID]);

ALTER TABLE [LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT PK_PERIOD PRIMARY KEY ([LOANNUMBER],[CYCLEDATE]);

ALTER TABLE [dbo].[US_ZIPCODES]
ADD CONSTRAINT PK_ZIPCODE PRIMARY KEY ([ZIP]);

--We also altered to add our foregin keys which will be used to reference tables accross the database

ALTER TABLE [LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT PK_PERIODLOAN FOREIGN KEY ([DELINQUENCYCODE]) REFERENCES [LOAN].[LU_DELINQUENCY] ([DELINQUENCYCODE]);

ALTER TABLE [LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT PK_PERIODIC_LOAN FOREIGN KEY ([LOANNUMBER]) REFERENCES [LOAN].[LOAN_SETUP_INFORMATION] ([LOANNUMBER]);

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT PK_SETUP_INFO FOREIGN KEY ([UNDERWRITERID]) REFERENCES [LOAN].[UNDERWRITER] ([UNDERWRITERID]);

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT PK_SETINFO FOREIGN KEY ([BORROWERID]) REFERENCES [BORROWER].[BORROWERINFO] ([BORROWERID]);

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT PK_SETUPINFO FOREIGN KEY ([PAYMENTFREQUENCY]) REFERENCES [LOAN].[LU_PAYMENTFREQUENCY] ([PAYMENTFREQUENCY]);

ALTER TABLE [dbo].[US_ZIPCODES]
ADD CONSTRAINT PK_ZIP FOREIGN KEY ([STATE_ID]) REFERENCES  [LOAN].[UNDERWRITER]([UNDERWRITERID]);

ALTER TABLE [BORROWER].[BORROWERADDRESS]
ADD CONSTRAINT PK_BORROWERADD FOREIGN KEY ([ZIP]) REFERENCES [dbo].[US_ZIPCODES] ([ZIP]);

ALTER TABLE [BORROWER].[BORROWERADDRESS]
ADD CONSTRAINT PK_BORROW FOREIGN KEY ([BORROWERID]) REFERENCES [BORROWER].[BORROWERINFO] ([BORROWERID]);


--We also did a validation on our table with email address to ensure each email input 
--is done correctly using the @ function

ALTER TABLE [BORROWER].[BORROWERINFO]
ADD CONSTRAINT CK_EMAIL_VALID CHECK  (EMAIL LIKE '%@%');

ALTER TABLE [LOAN].[UNDERWRITER]
ADD CONSTRAINT CK_EMAILS_VALID CHECK  (EMAIL LIKE '%@%');

--Also our board of director had some requirement to ensure only customer 18 and above can be granted a loan or
--borrow from the bank and we had to put that restriction on our database.

ALTER TABLE [BORROWER].[BORROWERINFO]
ADD CONSTRAINT CK_DATE_VALID CHECK  (DOB >= DATEADD(YEAR,-18,GETDATE()));

--The requirement also says phonenumber should only contact 10 character when input in the 
--database and we added that restriction using the Check function.--


ALTER TABLE [BORROWER].[BORROWERINFO]
ADD CONSTRAINT CK_PHONENUMBER CHECK (LEN([PHONENUMBER])=10);

--A restriction was required by BOD to ensure 9 character was inserted into the SSN

ALTER TABLE [BORROWER].[BORROWERINFO]
ADD CONSTRAINT CK_SSN CHECK (LEN([TAXPAYERID_SSN])=9);


--- A restriction was also added to this table column to ensure every value was added and if not value 
--proivided should be 0.which mean we cant have a blank column


ALTER TABLE[LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT DF_LOANPER DEFAULT 0 FOR [EXTRAMONTHPAYMENT];

-- A restriction was also added to this table column to ensure every value was added and if not value 
--proivided should be the current date of which the value was input.which mean we cant have a blank column


ALTER TABLE[BORROWER].[BORROWERINFO]
ADD CONSTRAINT DF_BORR DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE[BORROWER].[BORROWERADDRESS]
ADD CONSTRAINT DF_BORRADD DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE[LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT DF_PERLOAN DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE [dbo].[STATE]
ADD CONSTRAINT DF_STATEE DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE [dbo].[US_ZIPCODES]
ADD CONSTRAINT DF_ZZIP DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE [LOAN].[UNDERWRITER]
ADD CONSTRAINT DF_UNDER DEFAULT GETDATE() FOR CREATEDATE;

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT DF_SETIN DEFAULT GETDATE() FOR CREATEDATE;

---A restriction was also added to this table column to ensure every value inserted was unique and no replication--

ALTER TABLE [dbo].[STATE]
ADD CONSTRAINT UQ_STATES UNIQUE([STATENAME]);

ALTER TABLE [LOAN].[LOAN_PERIODIC]
ADD CONSTRAINT CK_PPLOAN CHECK([INTERESTPORTION]+[PRINCIPALPORTION]=[PAIDINSTALLMENT]);

---A restriction was also added to this table column to ensure every value was added was between the range
--of numbers

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT CK_LOANSET CHECK([LOANTERM] IN (35,30,15,10));

ALTER TABLE [LOAN].[LOAN_SETUP_INFORMATION]
ADD CONSTRAINT CK_LOANSETT CHECK([INTERESTRATE] >=0.01 AND [INTERESTRATE] <=0.30 );







